project_id = "hlalijpmqogytkwljppc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[edge_runtime]
enabled = true
port = 54329

[functions.chat-assistant]
verify_jwt = true

[functions.ask-docs]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false

[functions.analyze-flight-files]
verify_jwt = false

[functions.verify-secret]
verify_jwt = false

[functions.realtime-session-a330]
verify_jwt = false

[functions.vector-search-a330]
verify_jwt = false