// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlalijpmqogytkwljppc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsYWxpanBtcW9neXRrd2xqcHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjMwNTksImV4cCI6MjA2NTUzOTA1OX0.XARCWyiHn00F1u2bWBLD-f8Lzkw8mNA7jbCaUggz2eI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});